version: '3'
services:
  postgres_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_development
    ports:
      - "9999:5432"
